# config/app.yml for rails-settings-cached
defaults: &defaults
  address: ''
  copy_text: ''
  phone: ''
  twitter: ''
  youtube: ''
  facebook: ''
  google_plus: ''
  email_address: 'example@mail.com'
  default_from_email_address: 'example@mail.com'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
